xd/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("account/", views.home, name="home"),
    path("", views.home2, name="home2"),
    path("<int:year>/<str:month>/", views.home, name="home"),
    path("doctors/", views.doctor, name="doctors"),
    path("patients/", views.patient, name="patients"),
    path("appointments/", views.appointment, name="appointments"),
    path("add_appointment/", views.add_appointment, name = "add_appointment"),
    path("add_patient_or_doctor/", views.add_patient_or_doctor, name = "add_patient_or_doctor"),
    path("contact/", views.contact, name="contact"),
    path('get_doctors/', views.get_doctors, name='get_doctors'),
    path('get_available_times/', views.GetAvailableTimesView.as_view(), name='get_available_times'),
]

xd/xd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("myapp.urls")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

xd/myapp/models.py
from datetime import date, datetime, timedelta, time, timezone
from django.utils import timezone
from django.core.validators import RegexValidator, EmailValidator
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from babel.dates import format_date


# Create your models here.
class Day(models.Model):
    day = models.CharField(max_length=20)

    def __str__(self):
        return self.day


# DAYS_MAPPING = {
#     'Poniedziałek': 'Monday',
#     'Wtorek': 'Tuesday',
#     'Środa': 'Wednesday',
#     'Czwartek': 'Thursday',
#     'Piątek': 'Friday',
#     'Sobota': 'Saturday',
#     'Niedziela': 'Sunday',
# }
#
#
# def time_to_minutes(t):
#     return t.hour * 60 + t.minute


class Doctor(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    specialization = models.CharField(max_length=100)
    working_days = models.ManyToManyField(Day)
    working_hours_start = models.TimeField(default=time(8, 0))
    working_hours_end = models.TimeField(default=time(15, 0))
    visit_time = models.IntegerField(default=15)
    break_start = models.TimeField(default=time(12, 0))
    break_duration = models.IntegerField(default=15)

    def get_available_times(self, date):
        available_times = []
        day_of_week = format_date(date, 'EEEE', locale='pl_PL').capitalize()
        if day_of_week not in list(self.working_days.values_list('day', flat=True)):
            return available_times
        else:
            start_time = datetime.combine(date.min, self.working_hours_start)
            end_time = datetime.combine(date.min, self.working_hours_end)

            break_start = datetime.combine(date.min, self.break_start)
            break_end = break_start + timedelta(minutes=self.break_duration)

            current_time = start_time
            available_times = []
            while current_time + timedelta(minutes=self.visit_time) <= end_time:
                if not (break_start <= current_time < break_end):
                    if not Appointment.objects.filter(doctor=self, date=date, time=current_time.time()).exists():
                        available_times.append(current_time.time())
                current_time += timedelta(minutes=self.visit_time)
            return available_times

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Patient(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    email = models.EmailField(
        'User Email',
        default='xyz@wp.pl',
        unique=True,
        validators=[EmailValidator(message='Enter a valid email address.')]
    )
    first_name = models.CharField(
        max_length=100,
        validators=[RegexValidator(
            regex='^[a-zA-Z]*$',
            message='First name should only contain letters.'
        )]
    )
    last_name = models.CharField(
        max_length=100,
        validators=[RegexValidator(
            regex='^[a-zA-Z]*$',
            message='Last name should only contain letters.'
        )]
    )
    pesel = models.CharField(
        max_length=11,
        unique=True,
        validators=[RegexValidator(
            regex='^[0-9]*$',
            message='PESEL should only contain digits.'
        )]
    )
    birth_date = models.DateField()
    gender_choices = [('M', 'Male'), ('F', 'Female')]
    gender = models.CharField(max_length=1, choices=gender_choices)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    form_submitted = models.BooleanField(default=False)


class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    is_commercial = models.BooleanField(default=False)
    date = models.DateField(default='2015-05-06')
    time = models.TimeField(default=time(12, 0,0))

    # def clean(self):
    #     if not self.time:
    #         raise ValidationError(_('Nie wybrano godziny.'))
    #
    #     if self.date < timezone.now().date():
    #         raise ValidationError(_('Nie można wprowadzić daty z przeszłości.'))
    #
    #     if self.date == timezone.now().date() and self.time < timezone.now().time():
    #         raise ValidationError(_('Chyba nie zdążysz już przyjść? Ta godzina minęła.'))
    #
    #     day_of_week = format_date(self.date, 'EEEE', locale='pl_PL').capitalize()
    #     # print('day_of_week:', day_of_week)
    #     # working_days = list(self.doctor.working_days.values_list('day', flat=True))
    #     # print('working_days:', working_days)
    #     if day_of_week not in list(self.doctor.working_days.values_list('day', flat=True)):
    #         raise ValidationError(_('Wybrany lekarz nie pracuje w wybranym dniu.'))
    #
    #     if not (self.doctor.working_hours_start <= self.time <= self.doctor.working_hours_end):
    #         raise ValidationError(_('Wybrana godzina jest poza godzinami pracy lekarza.'))
    #
    #     break_end = (datetime.combine(date.min, self.doctor.break_start) + timedelta(
    #         minutes=self.doctor.break_duration)).time()
    #     if self.doctor.break_start <= self.time <= break_end:
    #         raise ValidationError(_('Wybrana godzina koliduje z przerwą lekarza.'))

    def save(self, *args, **kwargs):
        if not self.pk:
            available_times = self.doctor.get_available_times(self.date)
            if available_times:
                self.time = available_times[0]

        self.clean()
        super().save(*args, **kwargs)

xd/myapp/forms.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from .models import Appointment, Patient, Doctor
from django.utils import timezone
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError
import datetime
from datetime import date, datetime
from django.contrib.admin.widgets import AdminDateWidget


class AppointmentForm(forms.ModelForm):
    specialization = forms.ChoiceField(
        choices=Doctor.objects.values_list('specialization', 'specialization').distinct()
    )
    doctor = forms.ModelChoiceField(queryset=Doctor.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.ChoiceField(choices=[])

    class Meta:
        model = Appointment
        fields = ('specialization', 'doctor', 'is_commercial', 'date', 'time')
        widgets = {
            'is_commercial': forms.Select(attrs={'class': 'form-control'}, choices=[('T', 'True'), ('F', 'False')]),
            'specialization': forms.Select(attrs={'class': 'form-control', 'id': 'id_specialization'}),
            'doctor': forms.Select(attrs={'class': 'form-control', 'id': 'id_doctor'}),
            'time': forms.Select(attrs={'class': 'form-control', 'id': 'id_time'}),
        }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     print(f"self.instance: {self.instance}")
    #     print(f"self.instance.pk: {self.instance.pk if self.instance else None}")
    #     doctor_id = self.data.get('doctor')
    #     print(f"doctor_id: {doctor_id}")
    #     if doctor_id:
    #         doctor = Doctor.objects.get(pk=doctor_id)
    #         print(f"doctor: {doctor}")
    #         available_times = doctor.get_available_times(date.today())
    #         print(f"available_times: {available_times}")
    #         self.fields['time'].choices = [
    #             (time, time.strftime('%H:%M:%S')) for time in available_times
    #         ]
    #     else:
    #         available_times = Doctor.objects.first().get_available_times(date.today())
    #         print(f"available_times: {available_times}")
    #         self.fields['time'].choices = [
    #             (time, time.strftime('%H:%M:%S')) for time in available_times
    #         ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['time'].choices = [
                (time, time.strftime('%H:%M:%S')) for time in self.instance.doctor.get_available_times(self.instance.date)
            ]
        else:
            self.fields['time'].choices = [
                (time, time.strftime('%H:%M:%S')) for time in Doctor.objects.first().get_available_times(date.today())
            ]

    def clean(self):
        cleaned_data = super().clean()
        doctor = cleaned_data.get('doctor')
        date = cleaned_data.get('date')
        time = cleaned_data.get('time')

        # if doctor and date:
        #     available_times = [
        #         (time, time.strftime('%H:%M:%S')) for time in doctor.get_available_times(date)
        #     ]
        #     self.fields['time'].choices = available_times
        #
        # return cleaned_data

        # if doctor and date and time:
        #     datetime_combined = datetime.combine(date, time)
        #     if datetime_combined < timezone.now():
        #         raise forms.ValidationError("Data i czas muszą być przyszłe")
        #
        #     # Check if the doctor is not None before accessing its properties
        #     if doctor:
        #         if Appointment.objects.filter(doctor=doctor, date=date, time=time).exists():
        #             raise forms.ValidationError("Ten termin jest już zajęty")



# TO DZIAŁA ALE ZAPISUJEMY SIĘ O PÓŁNOCY W JAKIKOLWIEK DZIEŃ CHCEMY
# class AppointmentForm(ModelForm):
#     class Meta:
#         model = Appointment
#         fields = ('doctor', 'is_commercial', 'date', 'time')
#         widgets = {
#             'doctor': forms.Select(attrs={'class': 'form-control'}),
#             'is_commercial': forms.Select(attrs={'class': 'form-control'}, choices=[('T', 'True'), ('F', 'False')]),
#             'date': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}),
#             'time': forms.Select(attrs={'class': 'form-control'}),
#         }

    # def clean_date(self):
    #     date = self.cleaned_data.get('date')
    #     if date and date < timezone.now():
    #         raise ValidationError("Data musi być przyszła")
    #     return date
    #
    # def clean(self):
    #     cleaned_data = super().clean()
    #     doctor = cleaned_data.get('doctor')
    #     date = cleaned_data.get('date')
    #     if doctor and date:
    #         if Appointment.objects.filter(doctor=doctor, date=date).exists():
    #             raise ValidationError("Ten termin jest już zajęty")


class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = ('email', 'first_name', 'last_name', 'pesel', 'birth_date', 'gender')
        widgets = {
            'email': forms.EmailInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'pesel': forms.TextInput(attrs={'class': 'form-control'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'gender': forms.Select(attrs={'class': 'form-control'}, choices=[('M', 'Male'), ('F', 'Female')]),
        }

xd/myapp/views.py
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import model_to_dict
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
import calendar
from calendar import HTMLCalendar
from datetime import datetime
from babel.dates import format_date
from babel import Locale
from django.utils.html import format_html
from .forms import AppointmentForm, PatientForm
from django.http import HttpResponseRedirect, JsonResponse
from django.views import View
from .models import Doctor, Patient, Appointment, UserProfile
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request, year=datetime.now().year, month=datetime.now().strftime('%B')):
    name = request.user.first_name
    month = month.title()
    month_number = list(calendar.month_name).index(month)
    month_number = int(month_number)
    cal = HTMLCalendar().formatmonth(year, month_number)
    locale = Locale('pl_PL')
    now = datetime.now()
    current_data = now.date()
    time = now.strftime('%H:%M')
    formatted_date = format_date(current_data, format='full', locale=locale)
    return render(request, "home.html", {
        "name": name,
        "year": year,
        "month": month,
        "month_number": month_number,
        "cal": cal,
        "current_data": formatted_date,
        "time": time,

    })


def contact(request):
    return render(request, 'contact.html')


def home2(request):
    return render(request, 'home2.html')


def patient(request):
    patients = Patient.objects.all()
    return render(request, 'patients.html', {'patients': patients})


def doctor(request):
    doctors = Doctor.objects.all()
    specializations = Doctor.objects.values_list('specialization', flat=True).distinct()
    return render(request, 'doctors.html', {'doctors': doctors, 'specializations': specializations})



def appointment(request):
    patient = Patient.objects.get(user=request.user)
    appointments = Appointment.objects.filter(patient=patient)
    now = datetime.now()
    current_data = now.date()
    return render(request, 'appointments.html', {'appointments': appointments,
                                                 "current_data": current_data, })


@login_required
def get_doctors(request):
    specialization_id = request.GET.get('specialization_id')
    doctors = Doctor.objects.filter(specialization=specialization_id).values_list('id', 'first_name', 'last_name')
    doctors_list = list(doctors)
    return JsonResponse({'doctors': doctors_list})


class GetAvailableTimesView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        doctor_id = request.GET.get('doctor_id')
        date = request.GET.get('date')
        date = datetime.strptime(date, '%Y-%m-%d').date()
        doctor = Doctor.objects.get(id=doctor_id)
        available_times = doctor.get_available_times(date)
        return JsonResponse({'available_times': available_times})


def add_appointment(request):
    submitted = False
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            doctor = form.cleaned_data['doctor']
            appointment = form.save(commit=False)
            appointment.patient = Patient.objects.get(user=request.user)
            appointment.doctor = doctor
            appointment.save()
            submitted = True
    else:
        form = AppointmentForm()

    return render(request, 'add_appointment.html', {'form': form, 'submitted': submitted})


@login_required
def add_patient_or_doctor(request):
    profile, created = UserProfile.objects.get_or_create(user=request.user)
    submitted = profile.form_submitted
    patient = None
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.user = request.user
            patient.save()
            profile.form_submitted = True
            profile.save()
            submitted = True
    try:
        patient = Patient.objects.get(user=request.user)
        form = PatientForm(initial=model_to_dict(patient))
        submitted = True
    except Patient.DoesNotExist:
        form = PatientForm(initial={'email': request.user.email, 'first_name': request.user.first_name,
                                    'last_name': request.user.last_name})
    return render(request, 'add_patient_or_doctor.html', {'form': form, 'submitted': submitted, 'patient': patient})

xd/myapp/templates/add_appointment.html
{% extends "base.html" %}
{% block title %}
    Dodaj wizytę
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <center>
            <div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
                <h1 style="color: #3498db;">Dodaj wizytę</h1>
                <br/><br/>
                {% if submitted %}
                    <div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
                        <h1 style="color: #3498db;">Twoja wizyta została zarezerwowana!!!</h1>
                    </div>
                {% else %}
                    <form id="appointment-form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </form>
                {% endif %}
            </div>
        </center>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script>
            $(document).ready(function() {
    $('#id_specialization').change(function() {
        var specialization_id = $(this).val();
        $.ajax({
            url: '{% url "get_doctors" %}',
            data: {'specialization_id': specialization_id},
            dataType: 'json',
            success: function(data) {
                var options = '<option value="">---------</option>';
                for (var i = 0; i < data.doctors.length; i++) {
                    var doctor = data.doctors[i];
                    options += '<option value="' + doctor[0] + '">' + doctor[1] + ' ' + doctor[2] + '</option>';
                }
                $('#id_doctor').html(options);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.error("Błąd żądania AJAX: " + textStatus, errorThrown);
            }
        });
    });

    $('#id_date').change(function() {
        var doctor_id = $('#id_doctor').val();
        var date = $(this).val();
        if (doctor_id && date) {
            $.ajax({
                url: '{% url "get_available_times" %}',
                data: {'doctor_id': doctor_id, 'date': date},
                dataType: 'json',
                success: function(data) {
                    var options = '<option value="">---------</option>';
                    for (var i = 0; i < data.available_times.length; i++) {
    options += '<option value="' + data.available_times[i] + '">' + data.available_times[i] + '</option>';
}
                    $('#id_time').html(options);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.error("Błąd żądania AJAX: " + textStatus, errorThrown);
                }
            });
        }
    });
});
        </script>
    {% endif %}
{% endblock %}


xd/myapp/templates/add_patient_or_doctor.html
{% extends "base.html" %}
{% block title %}
    Formularz
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
	<div class="container">
        <h1 style="color: #3498db;">Formularz z danymi</h1>
	{% if submitted %}
			<div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Twoje dane zostały zapisane!</h4>
        <p>Niżej przedstawiliśmy Twoje dane. Jeżeli coś się nie zgadza, proszę zadzwoń do nas lub napisz maila:</p>
        <hr>
        <p class="mb-0">Telefon: 509 621 007 <br> Mail: przychodnia@wp.pl</p>
      </div>
			<div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Pacjent: {{ patient.first_name }} {{ patient.last_name }}</h5>
          <p class="card-text">Email: {{ patient.email }}</p>
          <p class="card-text">PESEL: {{ patient.pesel }}</p>
          <p class="card-text">Data urodzenia: {{ patient.birth_date }}</p>
          <p class="card-text">Płeć: {{ patient.get_gender_display }}</p>
        </div>
      </div>
	{% else %}
		<p>W tej części proszę abyś uzupełnił swoje dane jako pacjent. Dzięki temu znajdziesz się w naszej bazie pacjentów i będziesz mógł zapisywać się na badania. Do zobaczenia na wizycie!<br>
        Pamiętaj, że PESEL składa się tylko z cyfr! Jeżeli wpiszesz niedozowolony znak lub pomylisz się w numerze PESEL i wpiszesz już istniejący w bazie - formularz zostanie zwrócony. Jeżeli Twoje dane nie zostały zapisane wpisz je jeszcze raz uważnie. W razie problemów skonatkuj się z nami.</p>
		<form action="" method=POST enctype="multipart/form-data" class="needs-validation" novalidate>
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-primary" type="submit">Submit</button>
		</form>
	{% endif %}
	</div>
{% endif %}
{% endblock %}

xd/myapp/templates/appointments.html
{% extends "base.html" %}
{% block title %}
    Lista wizyt
{% endblock %}
{% block content %}
    <div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
        <h1 style="color: #3498db;">Lista wizyt</h1>

        <div style="border: 1px solid #ddd; padding: 20px; border-radius: 8px; background-color: white; margin-bottom: 20px; text-align: left;">
            <h2 style="color: #3498db; margin-bottom: 20px; text-align: center;">Oczekujące wizyty</h2>
            <ul style="list-style-type: none; padding: 0;">
                {% for appointment in appointments %}
                    {% if appointment.date >= current_data %}
                        <li style="margin-bottom: 10px;">
                            Pacjent: {{ appointment.patient }}<br>
                            Lekarz: {{ appointment.doctor }}<br>
                            Data: {{ appointment.date }}<br>
                            Komercyjna wizyta: {% if appointment.is_commercial %}Tak{% else %}Nie{% endif %}
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>

        <div style="border: 1px solid #ddd; padding: 20px; border-radius: 8px; background-color: white; text-align: left;">
            <h2 style="color: #3498db; margin-bottom: 20px; text-align: center;">Zrealizowane wizyty</h2>
            <ul style="list-style-type: none; padding: 0;">
                {% for appointment in appointments %}
                    {% if appointment.date < current_data %}
                        <li style="margin-bottom: 10px;">
                            Pacjent: {{ appointment.patient }}<br>
                            Lekarz: {{ appointment.doctor }}<br>
                            Data: {{ appointment.date }}<br>
                            Komercyjna wizyta: {% if appointment.is_commercial %}Tak{% else %}Nie{% endif %}
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}


xd/myapp/templates/contact.html
{% extends "base.html" %}
{% block title %}
Kontakt{% endblock %}
{% block content %}
<div class="container py-5 text-center" style="background-color: #f7f7f7;">
    <h1 class="display-4 text-primary">Kontakt</h1>
    <p class="lead">
        Telefon: 509 621 007 <br>
        Mail: przychodnia@wp.pl <br>
        Adres: ul. Przychodniowa 2, 84-200 Wejherowo
    </p>
</div>
{% endblock %}

xd/myapp/templates/doctors.html
{% extends "base.html" %}
{% block title %}
    Lekarze
{% endblock %}
{% block content %}
    <div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
        <h1 style="color: #3498db;">Lekarze</h1>

        <div style="border: 1px solid #ddd; padding: 20px; border-radius: 8px; background-color: white; margin-bottom: 20px; text-align: left;">
            <label for="specialization">Wybierz specjalizację:</label>
            <select id="specialization" name="specialization">
                <option value="">Wszystkie</option>
                {% for specialization in specializations %}
                    <option value="{{ specialization }}">{{ specialization }}</option>
                {% endfor %}
            </select>

            <ul id="doctor-list">
                {% for doctor in doctors %}
    <li class="doctor" data-specialization="{{ doctor.specialization }}">
        {{ doctor.first_name }} {{ doctor.last_name }}
        <ul>
            <li>Specjalizacja: {{ doctor.specialization }}</li>
            <li>Dni pracy: {{ doctor.get_working_days_display }}
                {% for day in doctor.working_days.all %}
                    {{ day.day }},
                {% endfor %}
            </li>
            <li>Godziny pracy: {{ doctor.working_hours_start|time:"H:i" }} - {{ doctor.working_hours_end|time:"H:i" }}</li>
        </ul>
    </li>
{% endfor %}

            </ul>
        </div>
    </div>

    <script>
        // Skrypt do filtrowania lekarzy po specjalizacji
        document.getElementById('specialization').addEventListener('change', function () {
            var selectedSpecialization = this.value;
            var doctorList = document.querySelectorAll('.doctor');

            doctorList.forEach(function (doctor) {
                var doctorSpecialization = doctor.getAttribute('data-specialization');
                if (selectedSpecialization === '' || selectedSpecialization === doctorSpecialization) {
                    doctor.style.display = 'list-item';
                } else {
                    doctor.style.display = 'none';
                }
            });
        });
    </script>
{% endblock %}

xd/myapp/templates/home.html
{% extends "base.html" %}

{% block title %}
    MEDRADAR
{% endblock %}

{% block content %}
    <style>
        .today {
            background-color: #3498db; /* Kolor tła dla dzisiejszej daty */
            color: #fff; /* Kolor tekstu dla dzisiejszej daty */
            border-radius: 50%; /* Zaokrąglenie kształtu dla efektu "koła" */
            padding: 5px; /* Dodatkowy padding dla lepszego wyglądu */
        }
    </style>

    <div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
        <h1 style="color: #3498db;">Dzień dobry, {{ name }}!</h1>
        <p style="font-size: 18px; color: #555; margin-bottom: 20px;">
            Dbaj o swoje zdrowie. Cieszymy się, że należysz do naszej przychodni. Razem zadbamy, aby nie tylko dziś było cudowne, ale i przyszłość! Bądź zdrów!
        </p>
        <div style="border: 1px solid #ddd; padding: 20px; border-radius: 8px; background-color: white;">
            <h2 style="color: #3498db; margin-bottom: 20px;">Twój kalendarz z wizytami</h2>
            <div style="overflow-x: auto; display: flex; align-items: center; justify-content: center;">
                {{ cal|safe }}
            </div>
            <div style="margin-top: 20px;">
                <p style="font-size: 18px; color: #555; margin-bottom: 10px;">Dzisiaj jest {{ current_data }}.</p>
            </div>
        </div>
    </div>
{% endblock %}





xd/myapp/templates/home2.html
{% extends "base.html" %}
{% block title %}
MEDRAR{% endblock %}
{% block content %}
<div style="background-color: #f7f7f7; padding: 20px; text-align: center;">
        <h1 style="color: #3498db;">Dołącz do nas!</h1>

    </div>
{% endblock %}

xd/myapp/templates/patients.html
{% extends "base.html" %}
{% block title %}
Patients{% endblock %}
{% block content %}
<h1>Patient List</h1>
    <ul>
        {% for patient in patients %}
            <li>
                {{ patient.first_name }} {{ patient.last_name }} - PESEL: {{ patient.pesel }}<br>

                Birth Date: {{ patient.birth_date }}<br>
                Gender: {{ patient.get_gender_display }}<br>
                Doctor: {{ patient.doctor }}<br>
                Commercial Visit: {% if patient.is_commercial %}Yes{% else %}No{% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}